import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[font]
normal = { family = "FiraCode Nerd Font Propo", style = "Retina" }
bold = { family = "FiraCode Nerd Font Propo", style = "Bold" }
italic = { family = "FiraCode Nerd Font Propo", style = "Light" }

size = 12
